version: "3.9"
services:
  go-mysql-service:
    container_name: go-mysql-service
    image: mysql:5.7
    ports:
    - "33066:3306"
    volumes:
      - goapp-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - message-app_backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
  goapp:
    container_name: goapp
    image: net.keithyw.goapp/goapp:latest
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - go-mysql-service
    networks:
      - message-app_backend  
    expose:
      - "8080"  
    # ports:
      # - "8080:8080"
    restart: on-failure
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      PORT: ${PORT}
      GRPC_HOST: ${GRPC_HOST}
    volumes:
      - .:/go/src/goapp  
  nginx:
    container_name: go-nginx-service
    build: "./nginx"
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "goapp"  
    networks:
      - message-app_backend  
  
volumes:
  goapp-mysql-data:

networks:
  message-app_backend:
    external: true

